### ISSUE TITLE
Move LICENSE to root directory

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#101]
Most projects keep their LICENSE file in the root directory. GitHub will also render a license logo with a short description on the front page if it is in the root directory. Both of these help with visibility for the license. We also don't have to carry many licenses in as directory the way astropy does; we inherited that structure from their repo template.

Proposal: ./licenses/LICENSE.rst -> ./LICENSE.rst and delete the licenses directory

**Comment by lauranuttall** [comment]
Task completed, see pull request [108](https://github.com/skypyproject/skypy/pull/108).
