### ISSUE TITLE
PyPI problems

### ISSUE THREAD

**Issue by itrharrison** [skypyproject/skypy#104]
On the PyPI website:
https://pypi.org/project/skypy/#history

There are a few small issues:

- Link to Homepage (skypy.info) is dead
- Link to https://libraries.io/pypi/skypy still contains reference to the Sky TV API

**Comment by rrjbca** [comment]
My understanding is @aamara registered the [skypy.info](https://skypy.info) domain but it is empty. In the meantime we could use [skypy.rtfd.org](https://skypy.rtfd.org)? We should definitely find a way to update the [libraries.io](https://libraries.io/pypi/skypy) page though.

**Comment by aamara** [comment]
link skypy.info now goes to https://skypyproject.github.io

Waiting for a response from libraries.io. I've asked them to switch to our Github rep.
