### ISSUE TITLE
Dependencies for build_docs not clear

### ISSUE THREAD

**Issue by spxiwh** [skypyproject/skypy#105]
I tried to run `python setup.py build_docs` on a local machine to see if there are any warnings in the sphinx build. However I see:

```
error: Sphinx and its dependencies must be installed for build_docs
```

What are the necessary dependencies here, e.g. what sphinx version is needed, does it need any add-ons like numpy does?

**Comment by spxiwh** [comment]
`sphinx_astropy` seems to be another thing needed here.

**Comment by rrjbca** [comment]
In the astropy [setup.cfg](https://github.com/astropy/astropy/blob/master/setup.cfg) file you can see they have an `[options.extras_require]` section defining extra requirements for `test`, `all` and `docs`. We should try and duplicate something like this and perhaps also document those requirements somewhere. Looking at our CI configs suggests `sphinx_astropy` (and its dependencies including sphinx) is the only extra requirement for building docs.

**Comment by ntessore** [comment]
Done in #196.
