### ISSUE TITLE
Sheth-Tormen halo mass function

### ISSUE THREAD

**Issue by itrharrison** [skypyproject/skypy#13]
## Description
Sophistication on the Press-Schechter halo mass function which includes effects from non-spherical collapse of haloes and has parameters tuned to a (relatively) primitive N-body simulation.

## Inputs
- Background cosmology
- Linear perturbation matter power spectrum

## Outputs
 - Catalogue of halo masses and redshifts

## References
- https://ui.adsabs.harvard.edu/link_gateway/2002MNRAS.329...61S/doi:10.1046/j.1365-8711.2002.04950.x

**Comment by rrjbca** [comment]
@gfavole I know you started work on this during v0.1 PR #72. We had to merge that PR into a temporary branch `skypyproject:sheth_tormen` when we made the repository public. We should decide if we are going to continue working on this or use e.g. colossus #16
