### ISSUE TITLE
v0.1 contributors to review details on DOI

### ISSUE THREAD

**Issue by itrharrison** [skypyproject/skypy#135]
The Zenodo DOI for v0.1:
https://zenodo.org/record/3755532

Autogenerates a lot of information, but people who are contributors may want to check that the following things are correctly included:

- Their name (spelled correctly)
- Their ORCID
- Their affiliation(s)
- Any grant they wish to be acknowledge (Zenodo can link to grants which are part of [OpenAIRE](https://explore.openaire.eu/search/software?softwareId=r37b0ad08687::506a75a3008f7c8b117e2727848344b2) and I have already done this for @sarahbridle's COSMICLENS).
- The keywords if they desire any others

**Comment by itrharrison** [comment]
Longer term we can set up a zenodo config file in the repository so we can manage this.

**Comment by itrharrison** [comment]
At the moment if you have a change you wish to be made, ask me or ask here!

**Comment by Lucia-Fonseca** [comment]
I'd rather my name not being spelled with the tilde -- although that's the correct spelling. Is that something I can change? I'm not sure how to do that

**Comment by Lucia-Fonseca** [comment]
> I'd rather my name not being spelled with the tilde -- although that's the correct spelling. Is that something I can change? I'm not sure how to do that

Lucia F. de la Bella 
that would be my prefer spelling

**Comment by gfavole** [comment]
should I add my name somewhere?

**Comment by itrharrison** [comment]
We are also trying to collect this information on the slack channel #author_info and have added a note in the slack greet bot for people to go there too.

**Comment by rrjbca** [comment]
Everybody should now have been added. For any amendments contact @itrharrison.
