### ISSUE TITLE
DEV: Add gas properties to galaxy clusters / haloes

### ISSUE THREAD

**Issue by bnord** [skypyproject/skypy#139]
## Description

We'll create a list of cluster gas properties -- intrinsic and observable --- based on halo properties.

## Inputs
 - halo properties (mass, redshift, shape)
 - multi-wavelength and intra-wavelength correlation (covariance) factors

## Outputs
 - Tsz
 - Ksz
 - Ysz
 - Lx
 - Tx
 - Yx

**Comment by bnord** [comment]
## Ideas
 - lognormal distributions of properties with covariances
 - power-law models of properties based on basic halo properties, like mass and redshift

**Comment by umetic** [comment]
Some references regarding intrinsic covariance of cluster properties (both theory and observations)
https://ui.adsabs.harvard.edu/abs/2014MNRAS.441.3562E/abstract
https://ui.adsabs.harvard.edu/abs/2018MNRAS.478.2618F/abstract 
https://ui.adsabs.harvard.edu/abs/2019NatCo..10.2504F/abstract
https://ui.adsabs.harvard.edu/abs/2020MNRAS.492.4528S/abstract
(and more)

**Comment by bnord** [comment]
design flow-through links to this question: https://github.com/skypyproject/skypy/issues/147#issuecomment-615288678

We might start with this issue and one on optical properties to decide which halo properties we need?

**Comment by itrharrison** [comment]
Issue deprecated by more specific examples. Please see Discussion pages for general discussion of which gas components and models to implement.
