### ISSUE TITLE
Think about unit conventions for spectra

### ISSUE THREAD

**Issue by philipp128** [skypyproject/skypy#145]
## Description
Especially in the field of spectra the used units are a mess. We should use the same convention. Any comments are welcome.

## Ideas
 - number of photons as unit for flux?

**Comment by bnord** [comment]
Does astropy have an convention here?
Or what about other projects that use astropy for spectra?

**Comment by bnord** [comment]
Perhaps we want at least two units:
photons as a baseline to consistent internally?
some other standard that matches to convention?

**Comment by rrjbca** [comment]
Astropy units: https://docs.astropy.org/en/stable/units/
Astropy magnitudes: https://docs.astropy.org/en/stable/units/logarithmic_units.html
We shouldn't need to worry about internal consistency if we use astropy units and equivalencies. Also we need to be using astropy functionality wherever possible as this is a requirement for astropy affiliation. If the astropy functionality is sufficient we should use that.

**Comment by ntessore** [comment]
It looks like most cases could be handled automatically using the `spectral_density(wav)` equivalency. That should transparently convert between pseudo-SEDs `f_lambda` and SEDs `lambda f_lambda`.

**Comment by ntessore** [comment]
So, am I right in thinking that the SED templates are in units of `synphot.units.FLAM/astropy.units.Msun`?

**Comment by philipp128** [comment]
Yes. Apparently that is the case.

**Comment by philipp128** [comment]
So yes. Now we need to find a way to include this in our sample. We also need to know whether we can use M_sun as a mass reference (in the same way as the 10 pc).

**Comment by ntessore** [comment]
In #242 we use the FLAM units `erg/s/cm2/A`. If multi-unit support becomes necessary, we can use Astropy's units to perform the conversion.
