### ISSUE TITLE
DM halo properties for clusters

### ISSUE THREAD

**Issue by aamara** [skypyproject/skypy#147]
Come up with a minimal list of the dark matter properties that are needed to model clusters.

**Comment by bnord** [comment]
Colossus doesn't appear to have velocity dispersion. (closest thing was spashback and a reference to circular velocities)

**Comment by bnord** [comment]
Ideas for list

- [ ] eccentricity
- [ ] mass
- [ ] angular momentum
- [ ] redshift
- [ ] radius
- [ ] concentration


 -

**Comment by bnord** [comment]
It seems like Colossus is the closest thing for this? 
Should we implement an import of that + our own basic versions of a few key things -- like some mass function?

**Comment by Lucia-Fonseca** [comment]
There is an issue regarding the implementation of COLOSSUS here #16.

**Comment by umetic** [comment]
Probably we may need velocity dispersions (at fixed halo mass) characterized from N-body simulations. Velocity anisotropy beta(r) in halos is quite substantial and strongly radially dependent.

It seems not that complicated for DM particles: Munari+13
https://ui.adsabs.harvard.edu/abs/2013MNRAS.430.2638M/abstract

I suppose it is also sensitivity to assembly histories (or dynamical state).
https://arxiv.org/abs/0909.4302

Velocity anisotropy beta(r) = 1-sigma_theta(r)^2/sigma_r(r)^2 (sigma_theta=sigma_phi assumed)

**Comment by bnord** [comment]
@umetic For the first simplest working version, should we consider the cluster properties as the thing we need to make sure we can achieve and work backward to halo properties?

**Comment by umetic** [comment]
> @umetic For the first simplest working version, should we consider the cluster properties as the thing we need to make sure we can achieve and work backward to halo properties?

I think it's a good idea.  We may work out the best way of characterizing cluster halos while working through.

**Comment by umetic** [comment]
> Ideas for list
> 
> * [ ]  eccentricity
> * [ ]  mass
> * [ ]  angular momentum
> * [ ]  redshift
> * [ ]  radius
> * [ ]  concentration

Thanks for the list!  

From the point of view of population modeling of DM halos as a whole, for a given cosmology and a mass function N(M200m,z) [+assuming an NFW profile), we should be able to specify and draw from PDFs(M, z) all relevant properties: halo concentration c200c=R200c/rs, ellipsoidal axis ratios (a/c, b/c), ... This picture ignores a lot of underlying physics (formation epochs, assembly histories), which is replaced by a set of intrinsic scatters.

Regarding the angular momentum, it is related with the orbital angular momentum beta(r) and also the central cusp slope of DM density (or the Einasto shape parameter). These quantities are more difficult to link with halo mass etc.

**Comment by ntessore** [comment]
Let's close this generic issue and open specific issue for the required dark matter properties, e.g. #234 requires the circular velocity #248.
