### ISSUE TITLE
Subhalos in parent halos

### ISSUE THREAD

**Issue by aamara** [skypyproject/skypy#148]
## Description

We need a function to add dark matter subhalo to a parent halo (section three of Vale and Ostriker 2005). Possibly related to #177.

## Inputs
 - Parent halo properties (mostly mass, but possibly also redshift).

## Outputs
 - List of subhalo properties.

## References
- [Vale and Ostriker, 2005, astro-ph/0511816.](https://arxiv.org/pdf/astro-ph/0511816.pdf)

**Comment by rrjbca** [comment]
We can follow [Vale & Ostriker 2004](https://arxiv.org/abs/astro-ph/0402500) Section 2: Subhalo Distribution relatively easily since we have already implemented the Press-Schechter mass function they use for subhalos.

**Comment by Lucia-Fonseca** [comment]
Is there a way I could edit the description, even if I did not open this issue?

**Comment by rrjbca** [comment]
If you have the right permissions there would be a white 'Edit' button above the 'assignees' on the right hand side. If you can't see that then let me know I would need to change your permissions.

**Comment by Lucia-Fonseca** [comment]
Yeah, sorry there is no `edit` bottom
