### ISSUE TITLE
Basic integration of photometric redshift codes

### ISSUE THREAD

**Issue by jucordero** [skypyproject/skypy#151]
## Description
For forecasting and specific survey comparisons, it can be useful to have estimations of redshifts using photometric redshift codes.
BPZ seems like a reasonable first candidate given its simple requirements in terms of inpunts and how they relate to what is already being developed for v0.1

## Inputs
The list of inputs depends on the specific photo-z code:
 - List of magnitude / fluxes and errors for individual objects
 - SED templates
 - Filter response curves
 - Training set with true redshifts
## Outputs
 - Photo-z point estimates 
 - Photo-z probability distribution

## References
 - Benítez N., 2000, ApJ, 536, 571

**Comment by jucordero** [comment]
@aamara mentioned on the skypy meeting that this issue should be only addressed once we have established a decent forward modelling pipeline before proceeding to the reverse problem.

**Comment by ntessore** [comment]
@jucordero do you have an idea how hard it is to call bpz from Python?

**Comment by ntessore** [comment]
closing this for now; will open a specific issue for integration with a given photo-z code as soon as the need arises
