### ISSUE TITLE
Interface with Colossus

### ISSUE THREAD

**Issue by itrharrison** [skypyproject/skypy#16]
## Description
Expresses the number density of collapsed dark matter haloes as a function of mass and redshift. Sampling from this creates a halo catalogue.

## Inputs
- Background cosmology
- Linear perturbation matter power spectrum

## Outputs
 - Catalogue of halo masses and redshifts

## References
- https://bdiemer.bitbucket.io/colossus/halo.html
- Online tool for calculating Halo Mass Functions http://hmf.icrar.org/
- http://astronomy.nmsu.edu/aklypin/COSMOLOGY/HaloMassFunction.pdf
- https://en.wikipedia.org/wiki/Press%E2%80%93Schechter_formalism

**Comment by bnord** [comment]
Does Colossus also do individual halo information, like density distribution, etc? Or is it just catalogs?

**Comment by rrjbca** [comment]
@bnord https://arxiv.org/pdf/1712.04512.pdf Table 3 lists the functions implemented including halo density profiles. Would any of those be sufficient?

**Comment by ntessore** [comment]
closing this for now as it's not scheduled for implementation in the next couple of releases; will revisit when the need arises
