### ISSUE TITLE
Galaxy stellar mass

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#160]
## Description
We require a function that measures the stellar mass of a galaxy from it's SED. Possibly related to #146 and #150. 

## Inputs
 - Galaxy spectral energy distribution

## Outputs
 - Galaxy stellar mass

**Comment by rrjbca** [comment]
Stellar masses are provided with the Blanton templates see Table 3: https://arxiv.org/pdf/astro-ph/0606170.pdf

**Comment by ntessore** [comment]
Stellar masses can either be sampled directly (#211) or computed from the coefficients template coefficients (#213) and distance modulus. If the need arises we can implement a function that computes these explicitly.
