### ISSUE TITLE
Planning board

### ISSUE THREAD

**Issue by Lucia-Fonseca** [skypyproject/skypy#171]
## Description
Sometimes tracking what is been done on GitHub is not totally visible. There are some task-management apps to track progress. "Projects" on GitHub seems to offer a solution to this (see references).
## Advantages
 - We can see the status of some tasks:  "looking into", "planning to do", "in progress" and put individual entries
- It helps with task management as SkyPy grows bigger
- We know what everyone is working on and whether we can offer our help 
- It reduces misunderstandings 
- It fosters communication and trust

## Disadvantages
 - It probably needs to be set up and updated manually

## References
- https://help.github.com/assets/images/help/projects/project-board-basic-kanban-template.png

**Comment by rrjbca** [comment]
Setting these up for v0.2 was on my to-do list. But it's not obvious if anyone was actually using them or found them helpful for v0.1. They won't be effective unless people make meaningful use of other GitHub features, specifically issues and assignees.

**Comment by bnord** [comment]
Should we try kanbans for one sector of the v0.2 work and see if it is used well? I would be up for using it in clusters/haloes.

**Comment by Lucia-Fonseca** [comment]
Kanbans sounds as good as anything. Is this something we can integrate within slack or GitHub? 

However, the ideal would be to reduce the number of platforms/communication channels. Perhaps we would like to have a chat (next telecon) where we talk about the proper use of GitHub features and how we can make the most out of it. 

Then we can decide?

**Comment by rrjbca** [comment]
The project from v0.1 are here: https://github.com/orgs/skypyproject/projects

**Comment by Lucia-Fonseca** [comment]
Thanks, Richard. I have used them some times. Maybe now that we expect the number of issues and PR to become increasingly larger than in v0.1, this feature might become useful.

**Comment by bnord** [comment]
I've enjoyed using Github-based Kanbans in a minor way on some other projects. It has helped me to see the layout of the project and where things stand. I do agree with @rrjbca that we would need an implementation where people actively use the kanbans --- some of it is automatic, some of it isn't.

**Comment by bnord** [comment]
@Lucia-Fonseca yeah, maybe on the next telecon? 
Should we discuss then what the expected actions by developers would look like in the presence of a kanban with issues and pr's?

**Comment by Lucia-Fonseca** [comment]
Sounds reasonable. Many of us (at least myself) are learning by doing. So having some guidance on how to use some features seems like a fantastic idea.

**Comment by rrjbca** [comment]
I've set up projects for each of our subpackages. See https://github.com/skypyproject/skypy/projects. I'll go through and start adding issues to each projects now.

**Comment by Lucia-Fonseca** [comment]
Thanks, Richard!

**Comment by rrjbca** [comment]
Most of the issues have now been assigned to projects where appropriate. People should continue to add new issues to projects as they are opened. We can discuss how to make effective use of issues and projects on our next telecon.
