### ISSUE TITLE
Generate halo catalogues using PINOCCHIO

### ISSUE THREAD

**Issue by gfavole** [skypyproject/skypy#18]
## Description
PINOCCHIO is a fast method, based on Lagrangian perturbation theory, to generate catalogues of dark matter haloes with known mass, position, velocity and merger history. It is able to reproduce, with very good accuracy, the hierarchical formation of dark matter halos from a realization of an initial linear density perturbation field, given on a 3D grid.

## Inputs
 - background cosmology 

## Outputs
 - halo catalogues including positions, velocities and redshifts

## References
http://adlibitum.oats.inaf.it/monaco/pinocchio.html

**Comment by rrjbca** [comment]
We've talked a lot about using colossus #16, does PINOCCHIO offer similar functionality?

**Comment by ntessore** [comment]
closing this for now as it's not scheduled for implementation in the next couple of releases; will revisit when the need arises
