### ISSUE TITLE
Simple model for satellite quenching

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#184]
## Description
Implement the model proposed by @aamara where the probability of a subhalo's host galaxy being quenched is a fixed probability.

## Inputs
 - Number of subhalos
 - Quenching probability

## Outputs
 - Boolean array indicating which subhalo's host galaxies are satellite-quenched

**Comment by zh-beep** [comment]
@rrjbca Would I be able to work on this? If so, I had two questions: 
1. Would I also have access to an array of all the subhalos? 
2. Also, in what file are the directions on how to run the package?

**Comment by rrjbca** [comment]
Hello @zh-beep and thank you for your interest in the project. Unfortunately we are not accepting external contributions at this time.
