### ISSUE TITLE
Zenodo config file

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#189]
In v0.1 the author list for the Zenodo DOI was generated automatically from the repository contributor list. Going forward we want to maintain a `.zenodo.json` config file containing the following information for each author:

- Name
- Affiliation
- ORCID

We should also add an instruction in [CONTRIBUTING.md](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md) for new contributors to add their details to this file as part of their first pull request.

Open questions:

- In what order are we listing authors?
- How do we distinguish between project members and external contributors?

**Comment by itrharrison** [comment]
I would argue in favour of authors being ordered alphabetically within groups. It may be the case that we are more granular in groups, but I think that is better than there only being a single slot ever available for a "first" author.

**Comment by itrharrison** [comment]
For groups, the simplest split could be:
- Members
- Non-member contributors

I would also suggest that non-contributing members should not be on a Version DoI (but they would of course remain on the Concept DoI).

If we still wanted to include non-contributing members on a Version DoI they should be distinguished:
- Contributing members
- Contributing non-members
- Non-contributing members

**Comment by itrharrison** [comment]
https://casrai.org/credit/

taxonomises 14(!) contributor roles.

How can the Zenodo DoI be organised? Can one person easily have multiple roles?

**Comment by rrjbca** [comment]
An example here of distinguishing between `creators` and different types of `contributors` e.g. `researchers`:

- https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/master/.zenodo.json
- https://zenodo.org/record/2658673

**Comment by itrharrison** [comment]
The list of allowed things seems to be here:
https://developers.zenodo.org/?python#representation

> * type: Contributor type. Controlled vocabulary (ContactPerson, DataCollector, DataCurator, DataManager,Distributor, Editor, Funder, HostingInstitution, Producer, ProjectLeader, ProjectManager, ProjectMember, RegistrationAgency, RegistrationAuthority, RelatedPerson, Researcher, ResearchGroup, RightsHolder,Supervisor, Sponsor, WorkPackageLeader, Other)

It doesn't specify whether or not multiple types are allowed (it seems not).

I will ask on slack what people think of these types and whether we want to use them.

**Comment by rrjbca** [comment]
Having looked again at our options I would suggest either:
```
creators: [ "The SkyPy Project", Alphabetical list of members ]
contributors: [ Alphabetical list of external contributors with type='Researcher' ]
```
or:
```
creators: [ "The SkyPy Project" ]
contributors: [ Alphabetical list of members with type='ProjectMember', 
                Alphabetical list of external contributors with type='Researcher' ]
```
Note that the bibliography entry will include the names of creators but not contributors. So with the second option the bibliography entry for the concept DOI would never change making it easier to cite but also nobody would be listed by name outside the zenodo page.

**Comment by itrharrison** [comment]
We have discussed this Issue at the v0.2 laptop-to-laptop meeting, and decided to go with @rrjbca's description above. Specifically:
```
creators: [ "The SkyPy Project" ]
contributors: [ Alphabetical list of members with type='ProjectMember', 
                Alphabetical list of external contributors with type='Other' ]
```
which will then appear in a BibTeX as:
```
@software{skypy_collaboration_2020_3755531,
  author       = {SkyPy Collaboration},
  title        = {SkyPy},
  month        = apr,
  year         = 2020,
  publisher    = {Zenodo},
  doi          = {10.5281/zenodo.3755531},
  url          = {https://doi.org/10.5281/zenodo.3755531}
}
```
