### ISSUE TITLE
transpose power spectra

### ISSUE THREAD

**Issue by ntessore** [skypyproject/skypy#195]
The power spectra are currently output which axes order `(nk, nz)`. This is the worse choice because it is always `P(k)` for a given `z` that is needed in computations, so the `P(k)` values for given `z` should always be contiguous in memory for the usual reasons. Which is also why every other power spectrum code returns `(nz, nk)`.

We had a vote and decided to change the order, which needs to happen before any code actually uses the power spectra.

**Comment by Lucia-Fonseca** [comment]
The halofit power spectrum from `_halofit.p` does seem to fail when the input redshift is a `numpy.ndarray`
