### ISSUE TITLE
Rerun yaml file requires to delete the output files

### ISSUE THREAD

**Issue by philipp128** [skypyproject/skypy#232]
**Describe the bug**
Re-running `.yaml ` files returns an error with the message that the output files already exist. 

**To Reproduce**
```
skypy -c examples/herbel_galaxies.yaml -f fits
```
```
skypy -c examples/herbel_galaxies.yaml -f fits
```

**Expected behavior**
It should run without problems and updating the output files.

**Comment by rrjbca** [comment]
The astropy `Table.write` method takes an optional argument `overwrite=True` that achieves this. This should probably be an extra flag for our command line script.
