### ISSUE TITLE
Wrong units for CAMB P(k)

### ISSUE THREAD

**Issue by itrharrison** [skypyproject/skypy#250]
**Describe the bug**
We currently return the output from the CAMB `get_matter_power_spectrum` function and assume these do not come with $h$ units. However, the output from this function does include those units.

We should instead use `get_matter_power_interpolator` which creates a spline interpolation for the matter power spectrum, and has a option to remove $h$ units. See below for this, and a comparison with the output from CLASS.

![camb_class_comparison](https://user-images.githubusercontent.com/3586409/90788481-c486e700-e2fd-11ea-8525-640924736a4e.png)

**Comment by rrjbca** [comment]
Or perhaps easier to just multiply through by the appropriate factor of h? No need to do interpolation if we already have the solution on the desired redshift-wavenumber grid.

**Comment by ntessore** [comment]
We actually have no guarantee that the `k` values from CAMB agree with our input. (I mean they do, but they don't have to, because CAMB could give back anything it wants.) So interpolation + evaluation at the input values might be the thing to do.

**Comment by rrjbca** [comment]
But then we also have no guarantee that the k values from the CAMB interpolator agree with our input? *shrug*

**Comment by ntessore** [comment]
You give CAMB `kmin`, `kmax`, and `nk` -- it could reasonably decide that the `k` resolution can be lower in the linear part and higher where the wiggles are. We are currently not checking that the returned `kh` correspond to our input `k` values, but using the interpolator to compute `P(k)` we wouldn't have to, even if the interpolator uses a non-uniform `k` grid internally.
