### ISSUE TITLE
Typo readme

### ISSUE THREAD

**Issue by Lucia-Fonseca** [skypyproject/skypy#256]
**Describe the bug**
There is a typo in the readme in the examples section

**To Reproduce**
1. Go to https://github.com/skypyproject/skypy
2.  Scroll down to 'examples'
4.  `skypy –config examples/herbel_galaxies.yaml –format fits`

**Expected behavior**
It should be `skypy –-config examples/herbel_galaxies.yaml –-format fits` 
Or am I mistaken?

**Comment by rrjbca** [comment]
Yes you're correct

**Comment by Lucia-Fonseca** [comment]
Ok. Let me change it

**Comment by rrjbca** [comment]
Although on the master branch we have also updated the script and changed config to a positional argument so now I think it should actually be:
`skypy examples/herbel_galaxies.yaml –-format fits`
