### ISSUE TITLE
move spectrum and magnitude functions to photometry module

### ISSUE THREAD

**Issue by ntessore** [skypyproject/skypy#288]
We have amassed a number of functions in `skypy.galaxy.spectrum` and `skypy.galaxy.luminosity` for working with spectra and magnitudes, but these functions are more generally useful and equally apply to the simulation of stars. I propose that we create a new `skypy.photometry` module where such functions can live.

**Comment by philipp128** [comment]
I'd say that all function from `skypy.galaxy.spectrum` except of `dirichlet_coefficients` and `stellar_mass_from_reference_band` should move to sth like `skypy.photometry`. Should we rename `skypy.galaxy.spectrum` is this case? So sth like `skypy.galaxy.photometry` to be consistent?

From `skypy.galaxy.luminosity` I suggest to move `absolute_to_apparent_magnitude`, `apparent_to_absolute_magnitude`, `luminosity_from_absolute_magnitude` and `absolute_magnitude_from_luminosity` to `skypy.photometry`.

However, we would still have `distance_modulus' in `skypy.galaxy.luminosity`. Maybe we can create a `skypy.astrophysics' module with basic astrophysical equations instead and put all of it in there?
