### ISSUE TITLE
download error message for external data required by skypy

### ISSUE THREAD

**Issue by sibirrer** [skypyproject/skypy#303]
**Describe the bug**
kcorrect.spec.ecsv loading did result to this error message (generated by skypy):
"data file not available: https://github.com/skypyproject/data/raw/1.0/spectrum_templates/kcorrect.spec.ecsv"

~/Software/skypy/skypy/galaxy/_spectrum_loaders.py in download_file(url, cache)
     22                 url, cache=cache, show_progress=False, **extra_kwargs)
     23     except urllib.error.URLError:  # pragma: no cover
---> 24         raise FileNotFoundError('data file not available: {}'.format(url))

This error message was misleading as the file is clearly available. Once out-commented the skypy exception the  `astropy.utils.data.download_file()` error resulted to 
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
which was more accurate of what the problem was.

**To Reproduce**
The problem is known for Python 3.6 (not for 3.5) and probably some specific security settings of macOS.
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error#comment94024091_45018725

**Expected behavior**
Do we need the skypy exception? or is the astropy error message sufficient? If the file is not too large (I know it's not code designed for version control), it might be more stable having it directly linked to the distribution or at least a more detailed error message also printing the error message of the underlying function (if this is possible).

**Desktop (please complete the following information):**
 - OS: [macOS Catalina 10.15.6]
 - Version [Pyton 3.6]

**Additional context**
Once the error is identified as a certificate issue, then this work-around might work for some people (not me):
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error#comment94024091_45018725

The reason this is still not working for me is because I have the macOS system python running (my bad) and this certificate can not be overwritten in this form (still try to figure this out). So I have not been able to run the rather simple skypy script and this might cause some people to not further go into the issue to fix it, especially when demonstration notebooks are using this functionality.

**Comment by ntessore** [comment]
This is a little out of our hands since it's a python distribution issue, but if it's popping up on macOS, I can only imagine how bad it will be on a managed supercomputer. In which case I'm also for bundling the data files, if not in `skypy` then perhaps in a separate `skypy-data` package.

**Comment by sibirrer** [comment]
That is at least for me a good idea having a separate skypy-data package. The issue is indeed not really a bug but might still affect a portion of the users undesirably.
