### ISSUE TITLE
Create a new issue template which is a feature request?

### ISSUE THREAD

**Issue by sarahbridle** [skypyproject/skypy#32]
Just a thought - maybe not necessary

**Comment by rrjbca** [comment]
We could probably just update `skypy/.github/ISSUE_TEMPLATE/new-model-proposal.md` and generalise it to be a "new feature" template which would cover both requests and proposals. We should probably also remove the language regarding "SkyPy Models" since that is a bit of an outdated concept now.

**Comment by philipp128** [comment]
Is this still necessary?
