### ISSUE TITLE
Update the skypy script documentation

### ISSUE THREAD

**Issue by ntessore** [skypyproject/skypy#320]
The documentation for the `skypy` command line script has not been updated to reflect all of the changes we have made for v0.3.

**Comment by rrjbca** [comment]
Suggestions for what needs doing:
- Move "Running skypy from the command line" above "Using a pipeline from other code" and add an example
- Update the "Config Files" subsection to accurately describe the new syntax
- Add a "Lightcone" section at the end with an example
