### ISSUE TITLE
Notebooks review

### ISSUE THREAD

**Issue by Lucia-Fonseca** [skypyproject/skypy#342]
## Description
With the upcoming PR with examples using Jupyter Notebooks, we need an efficient way to provide high-quality code review.
* GitHub renders the notebooks but does not allow comments.
* In PR mode, what appears is a JSON that is not easy to read.

There seem to be different (not completely satisfactory solutions)
* Leaving general comments, which spurs high-quality code review or make it too time-consuming.
* Using some tools like `ReviewNB` or `Jupytext` mentioned in [1].
* Duplicating the `*.ipynb` file and saving it as `*.py`, c.f. [2].

## References
 - [1] https://github.com/brian-rose/notebook_diff_tutorial
 - [2] https://medium.com/analytics-vidhya/creating-pull-requests-with-jupyter-notebooks-912520ee328f

**Comment by ntessore** [comment]
We are not using notebooks anymore — Richard R.
