### ISSUE TITLE
SkyPyLoader parses names as non-string variables

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#364]
The SkyPyLoader parses variable names using the same logic that it parses their values. As a result, variable names can take non-string types including int, float and astropy Quantity. Consider the config file:

```yml
# config.yml
42_km: 42 km
43 km: 43 km
```

``` python
>>> from skypy.pipeline import load_skypy_yaml
>>> config = load_skypy_yaml("./config.yml")
>>> print(config)

{'42_km': <Quantity 42. km>, <Quantity 43. km>: <Quantity 43. km>}
```

For the first entry, the key "42_km" is correctly interpreted as a string. However for the second entry  the key "43 km" is interpreted as an astropy Quantity by the same logic that applies to its corresponding value. This is problematic because `Pipeline.__getitem__` assumes all variable names in `state` are strings.

@ntessore pointed out that pyyaml will not let you apply different logic to keys and values when parsing files and therefore suggested that instead we enforce all variable names must be strings within the Pipeline class.

**Comment by JonathanDHarris** [comment]
@rrjbca  @ntessore  I've raised a PR, I'm dealing with it in the `config` class, rather than `Pipeline`.  It seemed neater to me, but feel free to weigh in.
