### ISSUE TITLE
update the name of the main branch

### ISSUE THREAD

**Issue by bnord** [skypyproject/skypy#433]
**Describe the bug**
"Master" harkens a racist heritage and vocabulary. Could we change the name to 'Main' or something else?

**Expected behavior**
here's a way to do that: https://jarv.is/notes/github-rename-master/

**Comment by ntessore** [comment]
[here](https://github.com/skypyproject/skypy/search?q=master&type=code) is what needs changing — I don't think this is a problem for the contributors, everyone will need to checkout `main` and branch off from there for their next feature branch

**Comment by rrjbca** [comment]
Very happy with this suggestion. `main` is the new GH default so lets stick with that. Two things I can think of that also need updating:
- Branch protection rules
- Update base branch for open PRs

I'm happy to address this and would suggest the following (probably overly cautious) approach to prevent anything going wrong with our open PRs (which we have seen before):
- [ ] Open a new PR with the changes outlined by @ntessore using `master` as the base
- [ ] Create and push the new `main` branch as outlined by @bnord
- [ ] Apply the same branch protections from `master` to `main` (change the branch name pattern to `ma*`)
- [ ] Change the base branch for the PR in the first step to `main` and merge it
- [ ] Change the base branch for all other open PRs to `main`
- [ ] Change the default branch to `main` and delete `master`
- [ ] Change the branch protection name pattern to `main`

**Comment by CKrawczyk** [comment]
Any github actions that run on PR/merge into `master` will also need to be updated to `main`.

**Comment by rrjbca** [comment]
I believe most of the work required has been completed. The only outstanding changes are:
- [ ] make `main` the new default branch on GitHub
- [ ] delete `master` branch
- [ ] change the branch protection name pattern to `main`

@skypyproject/skypy-infrastructure @skypyproject/skypy-board would somebody please check the following before I go ahead with these final changes:
- [ ] https://github.com/skypyproject/skypy/pulls the base branch for all PRs is `skypyproject/main`
- [ ] https://skypy.readthedocs.io/en/latest/developer/contributing.html refers to the new `main` branch

**Comment by ntessore** [comment]
looks good to me, and if anything slips through it should not be difficult to fix it

**Comment by Lucia-Fonseca** [comment]
Looks good to me too.

**Comment by rrjbca** [comment]
Thanks, I have updated the default branch to `main`. I will wait for a short time (~1 week) before deleting `master` and closing this issue in case any unforeseen problems arise.

**Comment by rrjbca** [comment]
The switch to `main` as the new default branch has not encountered any issues so far. I have therefore deleted `master` and updated the branch protection rules. Closing.
