### ISSUE TITLE
Guide to Constructing Configuration Files - JOSS Review

### ISSUE THREAD

**Issue by rmorgan10** [skypyproject/skypy#444]
To make getting up and running as painless as possible for new users, I recommend a guide on how to go about writing a general configuration file. Clearly (based on the examples) there is a natural flow to the configuration file. It starts at the top with definitions of individual variables, then goes into the tables to produce, and within the table entries the characteristics of the objects to simulate are included. A "User Guide" page in the documentation could certainly provide a walkthrough of this flow and how to think through the process of creating a general configuration file.

Furthermore, a specific request I have for this sort of guide is to list all the filters that can be used. I was unable to find what the other options instead of "sdss2010-*" were in the galaxy photometry example. If you could point out where this documentation is (if I just missed it) that would also work for me.

**Comment by rmorgan10** [comment]
Linking https://github.com/openjournals/joss-reviews/issues/3056

**Comment by rrjbca** [comment]
@rmorgan10 thanks for the suggestion. We have a few comprehensive example config files, but agree we don't have any simpler examples to teach the syntax and explain how it works so this is important. @Lucia-Fonseca here is the list of syntax features I believe we need to cover:

- [ ] Define a variable
- [ ] Call a function
- [ ] Reference a variable
- [ ] Define the cosmology
- [ ] Define parameters
- [ ] Create a table
- [ ] Add a column
- [ ] Multi-column assignment
- [ ] table.init and table.complete dependencies

**Comment by philipp128** [comment]
> Furthermore, a specific request I have for this sort of guide is to list all the filters that can be used. I was unable to find what the other options instead of "sdss2010-*" were in the galaxy photometry example. If you could point out where this documentation is (if I just missed it) that would also work for me.

PR #457 addresses  this.

**Comment by rmorgan10** [comment]
> PR #457 addresses this.

This [additional documentation](https://speclite.readthedocs.io/en/latest/filters.html) looks great! Thanks for adding it
