### ISSUE TITLE
BUG: Allow `schechter_smf_mass` input parameter `alpha` to be array and callable

### ISSUE THREAD

**Issue by philipp128** [skypyproject/skypy#524]
## Description
The input parameter `alpha` ([here](https://github.com/skypyproject/skypy/blob/16b2d19a8e79d01b62ee3d563f184e22104207f5/skypy/galaxies/stellar_mass.py#L22)) of the method `schechter_smf_mass` in `skypy.galaxies.stellar_mass` should be allowed to be an array_like or callable parameter.

This is especially correlated to the method `schechter_smf` in `skypy.galaxies._schechter` ([here](https://github.com/skypyproject/skypy/blob/16b2d19a8e79d01b62ee3d563f184e22104207f5/skypy/galaxies/_schechter.py#L81)) where `alpha` is allowed to be array_like and callable and used to call `schechter_smf_mass`.

**Comment by rrjbca** [comment]
This is intended. Unlike varying m_star, each different value of alpha requires constructing a different CDF and we couldn't come up with an efficient way around this. You could add the `dependent_argument` decorator for consistency and to allow functions for alpha that return a single scalar value. However, I expect an implementation varying alpha for each galaxy would be non-trivial.

**Comment by philipp128** [comment]
@rrjbca true I remember our discussion now. I think we should then at least change the requirement of `alpha` in the docs of `schechter_lf` and `schechter_smf` to `alpha` being a scalar. Or that we enable a callable that returns a scalar value.
I prefer the first.

What do you think?

**Comment by rrjbca** [comment]
I would suggest adding the `@dependent_argument`  decorator to make it consistent with `schechter_lf_magnitude`

**Comment by philipp128** [comment]
Ok as we discussed it is intended so I close this issue.
