### ISSUE TITLE
code file cleanup

### ISSUE THREAD

**Issue by ntessore** [skypyproject/skypy#89]
There are a couple leftovers from package creation, such as `skypy/example_mod.py` and `skypy/example_subpkg`. They have served their purpose and need to go for v0.1.

**Comment by rrjbca** [comment]
Also `skypy/tests/test_example.py`

**Comment by rrjbca** [comment]
What about `skypy/data` and `skypy/extern`; they may serve a purpose in the future but do we want to ship them empty in v0.1?

**Comment by ntessore** [comment]
I'd keep them for the time being, removing `data` also needs a change to `setup.cfg`, so we might want to tackle this in infrastructure?

**Comment by rrjbca** [comment]
`.travis.yml` can also go now that we have switched to use GitHub Actions

**Comment by itrharrison** [comment]
Power spectrum models are currently named inconsistently:
https://skypy.readthedocs.io/en/stable/power_spectrum/index.html

e.g.
`skypy.power_spectrum.camb.camb` returns a P(k,z) and
`skypy.power_spectrum.eisenstein_hu.power_spectrum` returns a P(k,z).

My preference would be to rename functions according to the second scheme, so change to
`skypy.power_spectrum.camb.power_spectrum`

**Comment by rrjbca** [comment]
Resolved by #107; closing
