### ISSUE TITLE
v0.1 Documentation Hack

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#99]
In advance of v0.1 release we will have a hack to fix and improve existing documentation. The documentation can be viewed [here](https://skypy.readthedocs.io/en/stable/). Some issues already identified:

- ~No documentation for `skypy.halo.mass` (AL) or `skypy.utils` (RR)~
- Documentation for SkyPyDriver rendering poorly
- ~CI badges on front page (GitHub actions, fix CircleCI,~ zenodo, ~pypi...)~
- ~Docstring for the whole package to the top-level ./skypy/__init__.py~
- ~On the repo homepage "No description, website, or topics provided."~

**Comment by jucordero** [comment]
A few typos in the Eisenstein & Hu module that I should fix.

**Comment by philipp128** [comment]
I found some typos in spectum.dirichlet_coefficients, redshift.herbel_redshift, redshift.herbel_pdf and luminosity.herbel_luminosity which I will work on.

**Comment by rrjbca** [comment]
Most of the issues identified here have now been addressed; great work everyone! I'll close this issue and open a separate issue specifically for the SkyPyDriver
